### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by siderorb** [l0b0/Exact-Editions-downloader#1]
I don't think this is working anymore. The script is unable to clean "issues" directory as it does not exist. I deleted the cleaning part of the script but the only thing it is able to do now is to generate an almost empty issues.html file. Probably the Exact Editions website has changed since 3 years ago, making the script unusable? Would it be possible to update it? Thank you very much!

**Comment by l0b0** [comment]
I made the last commit three years ago, and I've only used it about twice to download a magazine I was subscribed to, which now sadly no longer exists. If you want to make it work with the current website you'll have to look into it yourself, I'm afraid.
