### ISSUE TITLE
A how-to guide?

### ISSUE THREAD

**Issue by adamnowek** [l0b0/Exact-Editions-downloader#2]
Pardon my lack of knowledge, but I want to use this and I have zero idea what I'm looking at here. Can anyone explain this to me like I'm a child? I'm using Chrome on a Mac.

**Comment by l0b0** [comment]
This code has not been updated for six years, and was written with the sole purpose of downloading a now defunct Linux magazine in a readable format. Feel free to fork it, but I'm going to archive it since I'm not going to spend more time on it.
